// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvFroagubV1FEoicAG4hh3O_Y3q1jGmOQ',
    appId: '1:49456625906:web:e8b6f108688307720f386b',
    messagingSenderId: '49456625906',
    projectId: 'first24062',
    authDomain: 'first24062.firebaseapp.com',
    storageBucket: 'first24062.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqtV7cnxr3LI95sP9efB8GqsYmnds34QU',
    appId: '1:49456625906:android:7f41b4604a8bd4c20f386b',
    messagingSenderId: '49456625906',
    projectId: 'first24062',
    storageBucket: 'first24062.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe8VwkhefJAbxdipp6geMESHfTAemLZYo',
    appId: '1:49456625906:ios:5653744f0b71562c0f386b',
    messagingSenderId: '49456625906',
    projectId: 'first24062',
    storageBucket: 'first24062.appspot.com',
    androidClientId: '49456625906-dv2dc0tkhnafk9bur8b2iov9vgn5c3uu.apps.googleusercontent.com',
    iosBundleId: 'com.example.navigation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe8VwkhefJAbxdipp6geMESHfTAemLZYo',
    appId: '1:49456625906:ios:9c2fe0d17c21c86c0f386b',
    messagingSenderId: '49456625906',
    projectId: 'first24062',
    storageBucket: 'first24062.appspot.com',
    androidClientId: '49456625906-dv2dc0tkhnafk9bur8b2iov9vgn5c3uu.apps.googleusercontent.com',
    iosBundleId: 'com.example.navigation.RunnerTests',
  );
}
